name:                xmonad-dbus
version:             0.1.0.2
github:              "troydm/xmonad-dbus"
license:             BSD3
author:              "Dmitry Geurkov"
maintainer:          "d.geurkov@gmail.com"
copyright:           "2018-2023 Dmitry Geurkov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/xmonad-dbus#readme>

dependencies:
- base >= 4.7 && < 5
- dbus >= 0.10

library:
  source-dirs: src

executables:
  xmonad-dbus:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-dbus

tests:
  xmonad-dbus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-dbus
